<#
.SYNOPSIS
    Sample control for UniversalDashboard.
.DESCRIPTION
    Sample control function for UniversalDashboard. This function must have an ID and return a hash table.
.PARAMETER Id
    An id for the component default value will be generated by new-guid.
.EXAMPLE
    PS C:\> <example usage>
    Explanation of what the example does
.INPUTS
    Inputs (if any)
.OUTPUTS
    Output (if any)
.NOTES
    General notes
#>
function New-UDSemanticBreadcrumpDevider {
    param(
        [Parameter()]
        [string]$Text,

        [Parameter()]
        [string]$Icon
    )

    End {
        $Object = @{
            content = $Text
            icon = $Icon
        }

        $Object.PSTypeNames.Insert(0, 'UDSemantic.BreadcrumpDevider')

        return $Object
    }
}